CREATE TABLE TIMER (
  ID VARCHAR(36)   NOT NULL ,
  NAME VARCHAR(25)   NOT NULL ,
  PRIORITY INTEGER   NOT NULL   ,
PRIMARY KEY(ID)  );


CREATE UNIQUE INDEX TIME_GROUP_NAME ON TIMER (NAME);



CREATE TABLE DAY_GROUP (
  ID VARCHAR(36)   NOT NULL ,
  NAME VARCHAR(25)   NOT NULL ,
  READ_ONLY BOOL   NOT NULL ,
  TIMER_ID VARCHAR(36)      ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(TIMER_ID)
    REFERENCES TIMER(ID));


CREATE UNIQUE INDEX DAY_GROUP_NAME ON DAY_GROUP (NAME);
CREATE INDEX FK_TIMER_ID ON DAY_GROUP (TIMER_ID);



CREATE TABLE SPECIAL_DAY (
  ID VARCHAR(36)   NOT NULL ,
  DAY_TYPE VARCHAR(15)   NOT NULL ,
  DAY_VALUE INT   NOT NULL ,
  DESCRIPTION VARCHAR(25)    ,
  DAY_GROUP_ID VARCHAR(36)   NOT NULL   ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(DAY_GROUP_ID)
    REFERENCES DAY_GROUP(ID));


CREATE UNIQUE INDEX SPECIAL_DAY_TYP_VALUE ON SPECIAL_DAY (DAY_TYPE, DAY_VALUE);
CREATE INDEX FK_DAY_GROUP_ID ON SPECIAL_DAY (DAY_GROUP_ID);




